#!/bin/bash

for element in *
do
	if [ $element != "vetor.class" ] 
	then
		continue
	fi

	nome_arquivo=$(ls $element | awk -F '.' '{ print $1 }')
#	echo $nome_arquivo
	java $nome_arquivo  > resultado.txt
done
